namespace RapidCMS.ModelMaker.Enums
{
    public enum Color
    {
        PinkRed10,
        Red20,
        Red10,
        RedOrange10,
        Orange30,
        Orange20,
        Orange10,
        Yellow10,
        OrangeYellow20,
        OrangeYellow10,
        YellowGreen10,
        Green20,
        Green10,
        GreenCyan10,
        Cyan30,
        Cyan20,
        Cyan10,
        CyanBlue20,
        CyanBlue10,
        Blue10,
        BlueMagenta30,
        BlueMagenta20,
        BlueMagenta10,
        Magenta20,
        Magenta10,
        MagentaPink20,
        MagentaPink10,
        Gray40,
        Gray30,
        Gray20,
        Gray10
    }
}
