// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapidCMS.ModelMaker;

namespace RapidCMS.Example.ModelMaker.Migrations
{
    [DbContext(typeof(ModelMakerDbContext))]
    [Migration("20210620091459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RapidCMS.ModelMaker.OnetoManyMany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OneId");

                    b.ToTable("OnetoManyManys");
                });

            modelBuilder.Entity("RapidCMS.ModelMaker.OnetoManyOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OnetoManyOnes");
                });

            modelBuilder.Entity("RapidCMS.ModelMaker.OnetoManyMany", b =>
                {
                    b.HasOne("RapidCMS.ModelMaker.OnetoManyOne", "One")
                        .WithMany("Relation")
                        .HasForeignKey("OneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("One");
                });

            modelBuilder.Entity("RapidCMS.ModelMaker.OnetoManyOne", b =>
                {
                    b.Navigation("Relation");
                });
#pragma warning restore 612, 618
        }
    }
}
